# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controlUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 1032)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(820, 890, 451, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("hangyi.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(810, 960, 441, 51))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("robotlab.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(340, 80, 560, 51))
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(20, 220, 1201, 621))
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.workStartButton = QtWidgets.QPushButton(self.tab)
        self.workStartButton.setGeometry(QtCore.QRect(740, 110, 120, 45))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.workStartButton.setFont(font)
        self.workStartButton.setObjectName("workStartButton")
        self.workEndButton = QtWidgets.QPushButton(self.tab)
        self.workEndButton.setGeometry(QtCore.QRect(950, 110, 120, 45))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.workEndButton.setFont(font)
        self.workEndButton.setObjectName("workEndButton")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 120, 501, 321))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(25)
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget)
        self.label_24.setAcceptDrops(False)
        self.label_24.setAutoFillBackground(False)
        self.label_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_24.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 0, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget)
        self.label_32.setAcceptDrops(False)
        self.label_32.setAutoFillBackground(False)
        self.label_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_32.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 0, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget)
        self.label_36.setAcceptDrops(False)
        self.label_36.setAutoFillBackground(False)
        self.label_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_36.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.gridLayout.addWidget(self.label_36, 0, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget)
        self.label_25.setAcceptDrops(False)
        self.label_25.setAutoFillBackground(False)
        self.label_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_25.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 1, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget)
        self.label_31.setAcceptDrops(False)
        self.label_31.setAutoFillBackground(False)
        self.label_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_31.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 1, 2, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget)
        self.label_41.setAcceptDrops(False)
        self.label_41.setAutoFillBackground(False)
        self.label_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_41.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.gridLayout.addWidget(self.label_41, 1, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget)
        self.label_26.setAcceptDrops(False)
        self.label_26.setAutoFillBackground(False)
        self.label_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_26.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 2, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget)
        self.label_35.setAcceptDrops(False)
        self.label_35.setAutoFillBackground(False)
        self.label_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_35.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.gridLayout.addWidget(self.label_35, 2, 2, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget)
        self.label_39.setAcceptDrops(False)
        self.label_39.setAutoFillBackground(False)
        self.label_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_39.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.gridLayout.addWidget(self.label_39, 2, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget)
        self.label_28.setAcceptDrops(False)
        self.label_28.setAutoFillBackground(False)
        self.label_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_28.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 3, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget)
        self.label_30.setAcceptDrops(False)
        self.label_30.setAutoFillBackground(False)
        self.label_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_30.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 3, 2, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget)
        self.label_40.setAcceptDrops(False)
        self.label_40.setAutoFillBackground(False)
        self.label_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_40.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_40.setText("")
        self.label_40.setObjectName("label_40")
        self.gridLayout.addWidget(self.label_40, 3, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 4, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget)
        self.label_27.setAcceptDrops(False)
        self.label_27.setAutoFillBackground(False)
        self.label_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_27.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 4, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget)
        self.label_33.setAcceptDrops(False)
        self.label_33.setAutoFillBackground(False)
        self.label_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_33.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 4, 2, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget)
        self.label_38.setAcceptDrops(False)
        self.label_38.setAutoFillBackground(False)
        self.label_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_38.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.gridLayout.addWidget(self.label_38, 4, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 5, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget)
        self.label_29.setAcceptDrops(False)
        self.label_29.setAutoFillBackground(False)
        self.label_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_29.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 5, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget)
        self.label_34.setAcceptDrops(False)
        self.label_34.setAutoFillBackground(False)
        self.label_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_34.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 5, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget)
        self.label_37.setAcceptDrops(False)
        self.label_37.setAutoFillBackground(False)
        self.label_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_37.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.gridLayout.addWidget(self.label_37, 5, 3, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(260, 70, 361, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout.addWidget(self.label_23)
        self.layoutWidget2 = QtWidgets.QWidget(self.tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(740, 350, 331, 91))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(15)
        self.gridLayout_2.setVerticalSpacing(25)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_45.setAcceptDrops(False)
        self.label_45.setAutoFillBackground(False)
        self.label_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_45.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_45.setText("")
        self.label_45.setObjectName("label_45")
        self.gridLayout_2.addWidget(self.label_45, 0, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_47.setAcceptDrops(False)
        self.label_47.setAutoFillBackground(False)
        self.label_47.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_47.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_47.setText("")
        self.label_47.setObjectName("label_47")
        self.gridLayout_2.addWidget(self.label_47, 0, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_42.setObjectName("label_42")
        self.gridLayout_2.addWidget(self.label_42, 1, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_46.setAcceptDrops(False)
        self.label_46.setAutoFillBackground(False)
        self.label_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_46.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_46.setText("")
        self.label_46.setObjectName("label_46")
        self.gridLayout_2.addWidget(self.label_46, 1, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_48.setAcceptDrops(False)
        self.label_48.setAutoFillBackground(False)
        self.label_48.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_48.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_48.setText("")
        self.label_48.setObjectName("label_48")
        self.gridLayout_2.addWidget(self.label_48, 1, 2, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.tab)
        self.layoutWidget3.setGeometry(QtCore.QRect(880, 300, 211, 25))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_43 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_2.addWidget(self.label_43)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_2.addWidget(self.label_44)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.line = QtWidgets.QFrame(self.tab_2)
        self.line.setGeometry(QtCore.QRect(60, 80, 1011, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.tab_2)
        self.line_2.setGeometry(QtCore.QRect(60, 210, 1011, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_49 = QtWidgets.QLabel(self.tab_2)
        self.label_49.setGeometry(QtCore.QRect(60, 70, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.tab_2)
        self.label_50.setGeometry(QtCore.QRect(60, 200, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.tab_2)
        self.label_51.setGeometry(QtCore.QRect(90, 130, 121, 20))
        self.label_51.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_51.setObjectName("label_51")
        self.label_robot1_status = QtWidgets.QLabel(self.tab_2)
        self.label_robot1_status.setGeometry(QtCore.QRect(60, 130, 20, 20))
        self.label_robot1_status.setFrameShape(QtWidgets.QFrame.Box)
        self.label_robot1_status.setText("")
        self.label_robot1_status.setObjectName("label_robot1_status")
        self.label_robot2_status = QtWidgets.QLabel(self.tab_2)
        self.label_robot2_status.setGeometry(QtCore.QRect(250, 130, 20, 20))
        self.label_robot2_status.setFrameShape(QtWidgets.QFrame.Box)
        self.label_robot2_status.setText("")
        self.label_robot2_status.setObjectName("label_robot2_status")
        self.label_54 = QtWidgets.QLabel(self.tab_2)
        self.label_54.setGeometry(QtCore.QRect(280, 130, 121, 20))
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.tab_2)
        self.label_55.setGeometry(QtCore.QRect(470, 130, 121, 20))
        self.label_55.setObjectName("label_55")
        self.label_plc_status = QtWidgets.QLabel(self.tab_2)
        self.label_plc_status.setGeometry(QtCore.QRect(440, 130, 20, 20))
        self.label_plc_status.setFrameShape(QtWidgets.QFrame.Box)
        self.label_plc_status.setText("")
        self.label_plc_status.setObjectName("label_plc_status")
        self.label_57 = QtWidgets.QLabel(self.tab_2)
        self.label_57.setGeometry(QtCore.QRect(640, 130, 121, 20))
        self.label_57.setObjectName("label_57")
        self.label_pot_status = QtWidgets.QLabel(self.tab_2)
        self.label_pot_status.setGeometry(QtCore.QRect(610, 130, 20, 20))
        self.label_pot_status.setFrameShape(QtWidgets.QFrame.Box)
        self.label_pot_status.setText("")
        self.label_pot_status.setObjectName("label_pot_status")
        self.label_59 = QtWidgets.QLabel(self.tab_2)
        self.label_59.setGeometry(QtCore.QRect(820, 130, 121, 20))
        self.label_59.setObjectName("label_59")
        self.label_database_status = QtWidgets.QLabel(self.tab_2)
        self.label_database_status.setGeometry(QtCore.QRect(790, 130, 20, 20))
        self.label_database_status.setFrameShape(QtWidgets.QFrame.Box)
        self.label_database_status.setText("")
        self.label_database_status.setObjectName("label_database_status")
        self.label_61 = QtWidgets.QLabel(self.tab_2)
        self.label_61.setGeometry(QtCore.QRect(470, 270, 121, 20))
        self.label_61.setObjectName("label_61")
        self.label_raster3_status = QtWidgets.QLabel(self.tab_2)
        self.label_raster3_status.setGeometry(QtCore.QRect(440, 270, 20, 20))
        self.label_raster3_status.setFrameShape(QtWidgets.QFrame.Box)
        self.label_raster3_status.setText("")
        self.label_raster3_status.setObjectName("label_raster3_status")
        self.label_63 = QtWidgets.QLabel(self.tab_2)
        self.label_63.setGeometry(QtCore.QRect(640, 270, 121, 20))
        self.label_63.setObjectName("label_63")
        self.label_raster1_status = QtWidgets.QLabel(self.tab_2)
        self.label_raster1_status.setGeometry(QtCore.QRect(60, 270, 20, 20))
        self.label_raster1_status.setFrameShape(QtWidgets.QFrame.Box)
        self.label_raster1_status.setText("")
        self.label_raster1_status.setObjectName("label_raster1_status")
        self.label_65 = QtWidgets.QLabel(self.tab_2)
        self.label_65.setGeometry(QtCore.QRect(90, 270, 121, 20))
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.tab_2)
        self.label_66.setGeometry(QtCore.QRect(280, 270, 121, 20))
        self.label_66.setObjectName("label_66")
        self.label_raster2_status = QtWidgets.QLabel(self.tab_2)
        self.label_raster2_status.setGeometry(QtCore.QRect(250, 270, 20, 20))
        self.label_raster2_status.setFrameShape(QtWidgets.QFrame.Box)
        self.label_raster2_status.setText("")
        self.label_raster2_status.setObjectName("label_raster2_status")
        self.label_raster4_status = QtWidgets.QLabel(self.tab_2)
        self.label_raster4_status.setGeometry(QtCore.QRect(610, 270, 20, 20))
        self.label_raster4_status.setFrameShape(QtWidgets.QFrame.Box)
        self.label_raster4_status.setText("")
        self.label_raster4_status.setObjectName("label_raster4_status")
        self.label_69 = QtWidgets.QLabel(self.tab_2)
        self.label_69.setGeometry(QtCore.QRect(640, 350, 121, 20))
        self.label_69.setObjectName("label_69")
        self.label_radar12_status = QtWidgets.QLabel(self.tab_2)
        self.label_radar12_status.setGeometry(QtCore.QRect(250, 350, 20, 20))
        self.label_radar12_status.setFrameShape(QtWidgets.QFrame.Box)
        self.label_radar12_status.setText("")
        self.label_radar12_status.setObjectName("label_radar12_status")
        self.label_71 = QtWidgets.QLabel(self.tab_2)
        self.label_71.setGeometry(QtCore.QRect(470, 350, 121, 20))
        self.label_71.setObjectName("label_71")
        self.label_radar21_status = QtWidgets.QLabel(self.tab_2)
        self.label_radar21_status.setGeometry(QtCore.QRect(440, 350, 20, 20))
        self.label_radar21_status.setFrameShape(QtWidgets.QFrame.Box)
        self.label_radar21_status.setText("")
        self.label_radar21_status.setObjectName("label_radar21_status")
        self.label_73 = QtWidgets.QLabel(self.tab_2)
        self.label_73.setGeometry(QtCore.QRect(90, 350, 121, 20))
        self.label_73.setObjectName("label_73")
        self.label_radar22_status = QtWidgets.QLabel(self.tab_2)
        self.label_radar22_status.setGeometry(QtCore.QRect(610, 350, 20, 20))
        self.label_radar22_status.setFrameShape(QtWidgets.QFrame.Box)
        self.label_radar22_status.setText("")
        self.label_radar22_status.setObjectName("label_radar22_status")
        self.label_75 = QtWidgets.QLabel(self.tab_2)
        self.label_75.setGeometry(QtCore.QRect(280, 350, 121, 20))
        self.label_75.setObjectName("label_75")
        self.label_radar11_status = QtWidgets.QLabel(self.tab_2)
        self.label_radar11_status.setGeometry(QtCore.QRect(60, 350, 20, 20))
        self.label_radar11_status.setFrameShape(QtWidgets.QFrame.Box)
        self.label_radar11_status.setText("")
        self.label_radar11_status.setObjectName("label_radar11_status")
        self.label_laser12_status = QtWidgets.QLabel(self.tab_2)
        self.label_laser12_status.setGeometry(QtCore.QRect(250, 430, 20, 20))
        self.label_laser12_status.setFrameShape(QtWidgets.QFrame.Box)
        self.label_laser12_status.setText("")
        self.label_laser12_status.setObjectName("label_laser12_status")
        self.label_78 = QtWidgets.QLabel(self.tab_2)
        self.label_78.setGeometry(QtCore.QRect(90, 430, 121, 20))
        self.label_78.setObjectName("label_78")
        self.label_laser21_status = QtWidgets.QLabel(self.tab_2)
        self.label_laser21_status.setGeometry(QtCore.QRect(440, 430, 20, 20))
        self.label_laser21_status.setFrameShape(QtWidgets.QFrame.Box)
        self.label_laser21_status.setText("")
        self.label_laser21_status.setObjectName("label_laser21_status")
        self.label_80 = QtWidgets.QLabel(self.tab_2)
        self.label_80.setGeometry(QtCore.QRect(640, 430, 121, 20))
        self.label_80.setObjectName("label_80")
        self.label_laser11_status = QtWidgets.QLabel(self.tab_2)
        self.label_laser11_status.setGeometry(QtCore.QRect(60, 430, 20, 20))
        self.label_laser11_status.setFrameShape(QtWidgets.QFrame.Box)
        self.label_laser11_status.setText("")
        self.label_laser11_status.setObjectName("label_laser11_status")
        self.label_82 = QtWidgets.QLabel(self.tab_2)
        self.label_82.setGeometry(QtCore.QRect(280, 430, 121, 20))
        self.label_82.setObjectName("label_82")
        self.label_83 = QtWidgets.QLabel(self.tab_2)
        self.label_83.setGeometry(QtCore.QRect(470, 430, 121, 20))
        self.label_83.setObjectName("label_83")
        self.label_emergency_status = QtWidgets.QLabel(self.tab_2)
        self.label_emergency_status.setGeometry(QtCore.QRect(610, 430, 20, 20))
        self.label_emergency_status.setFrameShape(QtWidgets.QFrame.Box)
        self.label_emergency_status.setText("")
        self.label_emergency_status.setObjectName("label_emergency_status")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget_11 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_11.setGeometry(QtCore.QRect(650, 70, 381, 25))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget_11)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_329 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_329.setObjectName("label_329")
        self.horizontalLayout_9.addWidget(self.label_329)
        self.label_330 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_330.setObjectName("label_330")
        self.horizontalLayout_9.addWidget(self.label_330)
        self.label_331 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_331.setObjectName("label_331")
        self.horizontalLayout_9.addWidget(self.label_331)
        self.layoutWidget4 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget4.setGeometry(QtCore.QRect(141, 111, 391, 381))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(25)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_109 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_109.setObjectName("label_109")
        self.gridLayout_6.addWidget(self.label_109, 0, 0, 1, 1)
        self.label_110 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_110.setAcceptDrops(False)
        self.label_110.setAutoFillBackground(False)
        self.label_110.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_110.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_110.setText("")
        self.label_110.setObjectName("label_110")
        self.gridLayout_6.addWidget(self.label_110, 0, 1, 1, 1)
        self.label_111 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_111.setAcceptDrops(False)
        self.label_111.setAutoFillBackground(False)
        self.label_111.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_111.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_111.setText("")
        self.label_111.setObjectName("label_111")
        self.gridLayout_6.addWidget(self.label_111, 0, 2, 1, 1)
        self.label_113 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_113.setObjectName("label_113")
        self.gridLayout_6.addWidget(self.label_113, 1, 0, 1, 1)
        self.label_114 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_114.setAcceptDrops(False)
        self.label_114.setAutoFillBackground(False)
        self.label_114.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_114.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_114.setText("")
        self.label_114.setObjectName("label_114")
        self.gridLayout_6.addWidget(self.label_114, 1, 1, 1, 1)
        self.label_115 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_115.setAcceptDrops(False)
        self.label_115.setAutoFillBackground(False)
        self.label_115.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_115.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_115.setText("")
        self.label_115.setObjectName("label_115")
        self.gridLayout_6.addWidget(self.label_115, 1, 2, 1, 1)
        self.label_117 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_117.setObjectName("label_117")
        self.gridLayout_6.addWidget(self.label_117, 2, 0, 1, 1)
        self.label_118 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_118.setAcceptDrops(False)
        self.label_118.setAutoFillBackground(False)
        self.label_118.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_118.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_118.setText("")
        self.label_118.setObjectName("label_118")
        self.gridLayout_6.addWidget(self.label_118, 2, 1, 1, 1)
        self.label_119 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_119.setAcceptDrops(False)
        self.label_119.setAutoFillBackground(False)
        self.label_119.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_119.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_119.setText("")
        self.label_119.setObjectName("label_119")
        self.gridLayout_6.addWidget(self.label_119, 2, 2, 1, 1)
        self.label_121 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_121.setObjectName("label_121")
        self.gridLayout_6.addWidget(self.label_121, 3, 0, 1, 1)
        self.label_122 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_122.setAcceptDrops(False)
        self.label_122.setAutoFillBackground(False)
        self.label_122.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_122.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_122.setText("")
        self.label_122.setObjectName("label_122")
        self.gridLayout_6.addWidget(self.label_122, 3, 1, 1, 1)
        self.label_123 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_123.setAcceptDrops(False)
        self.label_123.setAutoFillBackground(False)
        self.label_123.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_123.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_123.setText("")
        self.label_123.setObjectName("label_123")
        self.gridLayout_6.addWidget(self.label_123, 3, 2, 1, 1)
        self.label_125 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_125.setObjectName("label_125")
        self.gridLayout_6.addWidget(self.label_125, 4, 0, 1, 1)
        self.label_126 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_126.setAcceptDrops(False)
        self.label_126.setAutoFillBackground(False)
        self.label_126.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_126.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_126.setText("")
        self.label_126.setObjectName("label_126")
        self.gridLayout_6.addWidget(self.label_126, 4, 1, 1, 1)
        self.label_127 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_127.setAcceptDrops(False)
        self.label_127.setAutoFillBackground(False)
        self.label_127.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_127.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_127.setText("")
        self.label_127.setObjectName("label_127")
        self.gridLayout_6.addWidget(self.label_127, 4, 2, 1, 1)
        self.label_129 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_129.setObjectName("label_129")
        self.gridLayout_6.addWidget(self.label_129, 5, 0, 1, 1)
        self.label_130 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_130.setAcceptDrops(False)
        self.label_130.setAutoFillBackground(False)
        self.label_130.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_130.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_130.setText("")
        self.label_130.setObjectName("label_130")
        self.gridLayout_6.addWidget(self.label_130, 5, 1, 1, 1)
        self.label_131 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_131.setAcceptDrops(False)
        self.label_131.setAutoFillBackground(False)
        self.label_131.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_131.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_131.setText("")
        self.label_131.setObjectName("label_131")
        self.gridLayout_6.addWidget(self.label_131, 5, 2, 1, 1)
        self.label_229 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_229.setObjectName("label_229")
        self.gridLayout_6.addWidget(self.label_229, 6, 0, 1, 1)
        self.label_231 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_231.setAcceptDrops(False)
        self.label_231.setAutoFillBackground(False)
        self.label_231.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_231.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_231.setText("")
        self.label_231.setObjectName("label_231")
        self.gridLayout_6.addWidget(self.label_231, 6, 1, 1, 1)
        self.label_230 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_230.setAcceptDrops(False)
        self.label_230.setAutoFillBackground(False)
        self.label_230.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_230.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_230.setText("")
        self.label_230.setObjectName("label_230")
        self.gridLayout_6.addWidget(self.label_230, 6, 2, 1, 1)
        self.label_233 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_233.setObjectName("label_233")
        self.gridLayout_6.addWidget(self.label_233, 7, 0, 1, 1)
        self.label_232 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_232.setAcceptDrops(False)
        self.label_232.setAutoFillBackground(False)
        self.label_232.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_232.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_232.setText("")
        self.label_232.setObjectName("label_232")
        self.gridLayout_6.addWidget(self.label_232, 7, 1, 1, 1)
        self.label_235 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_235.setAcceptDrops(False)
        self.label_235.setAutoFillBackground(False)
        self.label_235.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_235.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_235.setText("")
        self.label_235.setObjectName("label_235")
        self.gridLayout_6.addWidget(self.label_235, 7, 2, 1, 1)
        self.layoutWidget5 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget5.setGeometry(QtCore.QRect(140, 70, 411, 25))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_120 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_120.setObjectName("label_120")
        self.horizontalLayout_5.addWidget(self.label_120)
        self.label_112 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_112.setObjectName("label_112")
        self.horizontalLayout_5.addWidget(self.label_112)
        self.label_116 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_116.setObjectName("label_116")
        self.horizontalLayout_5.addWidget(self.label_116)
        self.layoutWidget6 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget6.setGeometry(QtCore.QRect(650, 110, 361, 81))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.layoutWidget6)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(25)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_332 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_332.setObjectName("label_332")
        self.gridLayout_10.addWidget(self.label_332, 0, 0, 1, 1)
        self.label_333 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_333.setAcceptDrops(False)
        self.label_333.setAutoFillBackground(False)
        self.label_333.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_333.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_333.setText("")
        self.label_333.setObjectName("label_333")
        self.gridLayout_10.addWidget(self.label_333, 0, 1, 1, 1)
        self.label_334 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_334.setAcceptDrops(False)
        self.label_334.setAutoFillBackground(False)
        self.label_334.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_334.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_334.setText("")
        self.label_334.setObjectName("label_334")
        self.gridLayout_10.addWidget(self.label_334, 0, 2, 1, 1)
        self.label_336 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_336.setObjectName("label_336")
        self.gridLayout_10.addWidget(self.label_336, 1, 0, 1, 1)
        self.label_337 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_337.setAcceptDrops(False)
        self.label_337.setAutoFillBackground(False)
        self.label_337.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_337.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_337.setText("")
        self.label_337.setObjectName("label_337")
        self.gridLayout_10.addWidget(self.label_337, 1, 1, 1, 1)
        self.label_335 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_335.setAcceptDrops(False)
        self.label_335.setAutoFillBackground(False)
        self.label_335.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_335.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_335.setText("")
        self.label_335.setObjectName("label_335")
        self.gridLayout_10.addWidget(self.label_335, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_338 = QtWidgets.QLabel(self.tab_4)
        self.label_338.setGeometry(QtCore.QRect(330, 120, 441, 231))
        self.label_338.setAutoFillBackground(True)
        self.label_338.setFrameShape(QtWidgets.QFrame.Box)
        self.label_338.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_338.setObjectName("label_338")
        self.tabWidget.addTab(self.tab_4, "")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(990, 100, 131, 20))
        self.label_7.setObjectName("label_7")
        self.label_whole_status = QtWidgets.QLabel(Form)
        self.label_whole_status.setGeometry(QtCore.QRect(1110, 100, 20, 20))
        self.label_whole_status.setFrameShape(QtWidgets.QFrame.Box)
        self.label_whole_status.setText("")
        self.label_whole_status.setObjectName("label_whole_status")
        self.layoutWidget7 = QtWidgets.QWidget(Form)
        self.layoutWidget7.setGeometry(QtCore.QRect(11, 940, 791, 27))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_3.setContentsMargins(3, 3, 3, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.label_login_time = QtWidgets.QLabel(self.layoutWidget7)
        self.label_login_time.setText("")
        self.label_login_time.setObjectName("label_login_time")
        self.horizontalLayout_3.addWidget(self.label_login_time)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.label_task_time = QtWidgets.QLabel(self.layoutWidget7)
        self.label_task_time.setObjectName("label_task_time")
        self.horizontalLayout_3.addWidget(self.label_task_time)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "主控界面"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:28pt; font-weight:600;\">无氰镀镉智能生产线中央控制系统</span></p></body></html>"))
        self.workStartButton.setText(_translate("Form", "启动生产"))
        self.workEndButton.setText(_translate("Form", "结束生产"))
        self.label_10.setText(_translate("Form", "工件1："))
        self.label_11.setText(_translate("Form", "工件2："))
        self.label_12.setText(_translate("Form", "工件3："))
        self.label_13.setText(_translate("Form", "工件4："))
        self.label_19.setText(_translate("Form", "工件5："))
        self.label_20.setText(_translate("Form", "工件6："))
        self.label_21.setText(_translate("Form", "工艺名"))
        self.label_22.setText(_translate("Form", "进度"))
        self.label_23.setText(_translate("Form", "工步状态"))
        self.label_9.setText(_translate("Form", "上料区："))
        self.label_42.setText(_translate("Form", "下料区："))
        self.label_43.setText(_translate("Form", "状态"))
        self.label_44.setText(_translate("Form", "推车id"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "   生产信息   "))
        self.label_49.setText(_translate("Form", "模块连接情况"))
        self.label_50.setText(_translate("Form", "传感器安全状态"))
        self.label_51.setText(_translate("Form", "轨道机器人模块1"))
        self.label_54.setText(_translate("Form", "轨道机器人模块2"))
        self.label_55.setText(_translate("Form", "现场PLC模块"))
        self.label_57.setText(_translate("Form", "电镀槽模块"))
        self.label_59.setText(_translate("Form", "数据库模块"))
        self.label_61.setText(_translate("Form", "安全光栅3"))
        self.label_63.setText(_translate("Form", "安全光栅4"))
        self.label_65.setText(_translate("Form", "安全光栅1"))
        self.label_66.setText(_translate("Form", "安全光栅2"))
        self.label_69.setText(_translate("Form", "激光雷达2-2"))
        self.label_71.setText(_translate("Form", "激光雷达2-1"))
        self.label_73.setText(_translate("Form", "激光雷达1-1"))
        self.label_75.setText(_translate("Form", "激光雷达1-2"))
        self.label_78.setText(_translate("Form", "激光测距1-1"))
        self.label_80.setText(_translate("Form", "急停按钮"))
        self.label_82.setText(_translate("Form", "激光测距1-2"))
        self.label_83.setText(_translate("Form", "激光测距2-1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "   安全信息   "))
        self.label_329.setText(_translate("Form", "机械臂信息："))
        self.label_330.setText(_translate("Form", "当前位置："))
        self.label_331.setText(_translate("Form", "运行状态："))
        self.label_109.setText(_translate("Form", "1号推车："))
        self.label_113.setText(_translate("Form", "2号推车："))
        self.label_117.setText(_translate("Form", "3号推车："))
        self.label_121.setText(_translate("Form", "4号推车："))
        self.label_125.setText(_translate("Form", "5号推车："))
        self.label_129.setText(_translate("Form", "6号推车："))
        self.label_229.setText(_translate("Form", "7号推车："))
        self.label_233.setText(_translate("Form", "8号推车："))
        self.label_120.setText(_translate("Form", "推车信息："))
        self.label_112.setText(_translate("Form", "当前位置："))
        self.label_116.setText(_translate("Form", "装挂状态："))
        self.label_332.setText(_translate("Form", "1号机械臂："))
        self.label_336.setText(_translate("Form", "2号机械臂："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "   设备信息   "))
        self.label_338.setText(_translate("Form", "当前无异常状态！"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "   异常处理   "))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">当前系统状态：</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">系统登陆时间：</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">当前任务开启时间：</span></p></body></html>"))
        self.label_task_time.setText(_translate("Form", "任务未开始"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">联合研发单位：</span></p></body></html>"))
